### ISSUE TITLE
Pagination - last page

### ISSUE THREAD

**Issue by asharma-r7** [rapid7/marionette.carpenter#28]
The issue occurs when there is an equal number of rows spanning across all pages and clicking on the 'last page' indicator. 

For example, a collection that contains 30 models is used with a table with the 'perPage' property set to 10. There will be 3 pages available to the user (with an exact amount of rows per page). Clicking on the 'last page' indicator on the Carpenter pagination area will display 'No items were found.', instead of the expected 10 items.

I put together a jsfiddle to illustrate the problem - http://jsfiddle.net/amito93/xb0grotj/

**Comment by mbuck-r7** [comment]
Thanks for the report! Awesome that you included an example. I'm not quite sure what's happening off the top of my head, so I'll have to dig in as soon as I have some extra bandwidth - which will be next week, at the earliest. We're using an old version of backbone paginator, so my initial suspicion would be that the problem lies there. We're planning on upgrading it as soon as we begin work on the new version of this component.

**Comment by asharma-r7** [comment]
Thanks!

**Comment by claughlin-r7** [comment]
fixed with #30
